### ISSUE TITLE
缺少 MustTryGet 方法

### ISSUE THREAD

**Issue by cmstar** [thisXYH/cache#2]
`CacheProvider` 上各个方法都有 `Must*` 版，只有 `TryGet` 没有。考虑：
1. 增加 `CacheProvider.MustTryGet` 。
2. 移除 `CacheProvider` 上的 `Must*` 方法，仅由 `KeyOperation` 实现。定在 `CacheProvider` 上导致实现缓存提供器难度增加，而 `Must*` 方法的代码则总是在每个实现上冗余。

**Comment by thisXYH** [comment]
是有这个问题，将在 issue#2 分支调整。

**Comment by thisXYH** [comment]
已处理 [commited](https://github.com/thisXYH/cache/commit/8d49222bf16a62402ba81106d333def8078bf7e8)
